// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sharpify.Core.Data;

#nullable disable

namespace Sharpify.Core.Migrations
{
    [DbContext(typeof(SharpifyDbContext))]
    [Migration("20260929022039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Sharpify.Core.Entities.AlbumArtist", b =>
                {
                    b.Property<string>("AlbumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistId")
                        .HasColumnType("TEXT");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("AlbumArtists");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.DownloadJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("YouTubeMatchId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TrackId");

                    b.HasIndex("YouTubeMatchId");

                    b.ToTable("DownloadJobs");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.PlaylistTrack", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistId", "TrackId");

                    b.HasIndex("Position");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistTracks");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.SpotifyAlbum", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.SpotifyArtist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Href")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.SpotifyPlaylist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Href")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.SpotifyTrack", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Explicit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isrc")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.TrackArtist", b =>
                {
                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistId")
                        .HasColumnType("TEXT");

                    b.HasKey("TrackId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("TrackArtists");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.YouTubeMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelTitle")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("MatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("YouTubeUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId")
                        .IsUnique();

                    b.ToTable("YouTubeMatches");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.AlbumArtist", b =>
                {
                    b.HasOne("Sharpify.Core.Entities.SpotifyAlbum", "Album")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sharpify.Core.Entities.SpotifyArtist", "Artist")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.DownloadJob", b =>
                {
                    b.HasOne("Sharpify.Core.Entities.SpotifyTrack", "Track")
                        .WithMany("DownloadJobs")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sharpify.Core.Entities.YouTubeMatch", "YouTubeMatch")
                        .WithMany("DownloadJobs")
                        .HasForeignKey("YouTubeMatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Track");

                    b.Navigation("YouTubeMatch");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.PlaylistTrack", b =>
                {
                    b.HasOne("Sharpify.Core.Entities.SpotifyPlaylist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sharpify.Core.Entities.SpotifyTrack", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.SpotifyTrack", b =>
                {
                    b.HasOne("Sharpify.Core.Entities.SpotifyAlbum", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.TrackArtist", b =>
                {
                    b.HasOne("Sharpify.Core.Entities.SpotifyArtist", "Artist")
                        .WithMany("TrackArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sharpify.Core.Entities.SpotifyTrack", "Track")
                        .WithMany("TrackArtists")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.YouTubeMatch", b =>
                {
                    b.HasOne("Sharpify.Core.Entities.SpotifyTrack", "Track")
                        .WithOne("YouTubeMatch")
                        .HasForeignKey("Sharpify.Core.Entities.YouTubeMatch", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.SpotifyAlbum", b =>
                {
                    b.Navigation("AlbumArtists");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.SpotifyArtist", b =>
                {
                    b.Navigation("AlbumArtists");

                    b.Navigation("TrackArtists");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.SpotifyPlaylist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.SpotifyTrack", b =>
                {
                    b.Navigation("DownloadJobs");

                    b.Navigation("PlaylistTracks");

                    b.Navigation("TrackArtists");

                    b.Navigation("YouTubeMatch");
                });

            modelBuilder.Entity("Sharpify.Core.Entities.YouTubeMatch", b =>
                {
                    b.Navigation("DownloadJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
